version: '2'

services:

  mysqldb_docker_test:
    container_name: mysqldb_docker_test
    build:
      context: ./mysql
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 53306:3306

  wildfly_docker_test:
    container_name: wildfly_docker_test
    build:
      context: ./wildfly
    ports:
      - 58080:8080
      - 59990:9990
    depends_on:
      - "mysqldb_docker_test"
    volumes:
      - ./wildfly/mysql-connector-java-5.1.30-bin.jar:/opt/jboss/wildfly/standalone/deployments/mysql-connector-java-5.1.30-bin.jar
      - ./wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml




